server:
  port: 7001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 10

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/engineer-yt-clone/configuration
          default-label: main
          timeout: 2
          clone-on-start: on
          force-pull: on

